- name: Install Ambari Server
  yum:
    name: ambari-server
    state: installed
  ignore_errors: true

- name: Setup Ambari Server
  shell: |
    ambari-server setup -s

- name: Setup HDF MPack
  shell: |
        echo yes | ambari-server install-mpack --mpack={{ hdf_ambari_mpack_url }} --purge --verbose
  ignore_errors: true
  
- name: Start Ambari Server
  service:
    name: ambari-server
    state: restarted
  ignore_errors: true


- name: Ensure Ambari Server starts during System Startup
  service:
    name: ambari-server
    enabled: yes
